In [0]:
# Obejects and map
# For tutorial only
# Haoyu Niu



In [0]:
class Person:
  department = 'EECS'

  def set_name(self, new_name):
    self.name = new_name
  def set_location(self, new_location):
    self.location = new_location
    

In [6]:
person = Person()
person.set_name('Haoyu Niu')
person.set_location('Atwater CA, USA')

print('{} lives in {} and works in the department {}'.format(person.name, person.location, person.department))


Haoyu Niu lives in Atwater CA, USA and works in the department EECS


In [9]:
store1 = [10.00, 11.00, 12, 2.34]
store2 = [9.00, 11.10, 12.34, 2.01]
cheapest = map(min, store1, store2)
cheapest

In [10]:
for item in cheapest:
  print(item)

9.0
11.0
12
2.01


In [12]:
my_function = lambda a, b, c : a + b
my_function(1,2,3)

3

In [13]:
my_list = []
for number in range(0,1000):
  if number % 2 ==0:
    my_list.append(number)
my_list

[0,
 2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98,
 100,
 102,
 104,
 106,
 108,
 110,
 112,
 114,
 116,
 118,
 120,
 122,
 124,
 126,
 128,
 130,
 132,
 134,
 136,
 138,
 140,
 142,
 144,
 146,
 148,
 150,
 152,
 154,
 156,
 158,
 160,
 162,
 164,
 166,
 168,
 170,
 172,
 174,
 176,
 178,
 180,
 182,
 184,
 186,
 188,
 190,
 192,
 194,
 196,
 198,
 200,
 202,
 204,
 206,
 208,
 210,
 212,
 214,
 216,
 218,
 220,
 222,
 224,
 226,
 228,
 230,
 232,
 234,
 236,
 238,
 240,
 242,
 244,
 246,
 248,
 250,
 252,
 254,
 256,
 258,
 260,
 262,
 264,
 266,
 268,
 270,
 272,
 274,
 276,
 278,
 280,
 282,
 284,
 286,
 288,
 290,
 292,
 294,
 296,
 298,
 300,
 302,
 304,
 306,
 308,
 310,
 312,
 314,
 316,
 318,
 320,
 322,
 324,
 326,
 328,
 330,
 332,
 334,
 336,
 338,
 340,
 342,
 344,
 346,
 348,
 350,

In [0]:
import numpy as np

In [15]:
mylist = [1,2,3]
x = np.array(mylist)
x

array([1, 2, 3])

In [0]:
y = np.array([4,5,6])

In [17]:
y

array([4, 5, 6])

In [19]:
m = np.array([[7,8,9],[10,11,12]])
m

array([[ 7,  8,  9],
       [10, 11, 12]])

In [20]:
m.shape

(2, 3)

In [0]:
n = np.arange(0,30,2)

In [22]:
n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [23]:
n = n.reshape(3,5)
n

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [27]:
o = np.linspace(0,4,9)
o

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

In [29]:
o.resize(3,3)
o

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ]])

In [30]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [31]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [32]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [33]:
np.diag(y)

array([[4, 0, 0],
       [0, 5, 0],
       [0, 0, 6]])

In [34]:
np.array([1,2,3]*3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [35]:
np.repeat([1,2,3],3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [36]:
p = np.ones([2,3],int)
p

array([[1, 1, 1],
       [1, 1, 1]])

In [37]:
np.vstack([p,2*p])

array([[1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2]])

In [38]:
np.hstack([p,2*p])

array([[1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2]])

In [0]:
# operations

In [40]:
print(x+y)

[5 7 9]


In [41]:
print(x-y)

[-3 -3 -3]


In [42]:
print(x*y)  # elementwise

[ 4 10 18]


In [43]:
print(x/y)

[0.25 0.4  0.5 ]


In [44]:
print(x**2)

[1 4 9]


In [45]:
x.dot(y)

32

In [0]:
z = np.array([y, y**2])

In [47]:
z

array([[ 4,  5,  6],
       [16, 25, 36]])

In [48]:
print(len(z))

2


In [49]:
z.shape

(2, 3)

In [50]:
z.T

array([[ 4, 16],
       [ 5, 25],
       [ 6, 36]])

In [51]:
z

array([[ 4,  5,  6],
       [16, 25, 36]])

In [52]:
z.dtype

dtype('int64')

In [53]:
z=z.astype('f')
z.dtype

dtype('float32')

In [0]:
a = np.array([-4,-2,1,3,5])

In [55]:
a.sum()

3

In [56]:
a.max()

5

In [57]:
a.mean()

0.6

In [59]:
a.std()

3.2619012860600183

In [60]:
a.argmax()

4

In [61]:
a.argmin()

0

In [0]:
s = np.arange(13)**2

In [63]:
s


array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144])

In [64]:
s[0],s[4],s[-1]

(0, 16, 144)

In [65]:
s[1:5]

array([ 1,  4,  9, 16])

In [66]:
s[-4:]

array([ 81, 100, 121, 144])

In [67]:
s[-5::-2]

array([64, 36, 16,  4,  0])

In [0]:
r = np.arange(36)

In [69]:
r

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [0]:
r.resize((6,6))

In [71]:
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [72]:
r[2,2]

14

In [73]:
r[3,3:6]

array([21, 22, 23])

In [74]:
r[r>30] = 30
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [0]:
r2 = r[:3,:3]

In [76]:
r2

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14]])

In [0]:
r2[:]=0

In [78]:
r2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [79]:
r

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [0]:
r_copy = r.copy()


In [81]:
r_copy


array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [82]:
test = np.random.randint(0,10,(4,3))
test

array([[5, 5, 7],
       [7, 1, 7],
       [5, 3, 8],
       [6, 0, 7]])

In [83]:
for row in test:
  print(row)

[5 5 7]
[7 1 7]
[5 3 8]
[6 0 7]


In [84]:
for i in range(len(test)):
  print(test[i])

[5 5 7]
[7 1 7]
[5 3 8]
[6 0 7]


In [85]:
for i, row in enumerate(test):
  print('row', i, 'is', row)

row 0 is [5 5 7]
row 1 is [7 1 7]
row 2 is [5 3 8]
row 3 is [6 0 7]


In [0]:
test2 = test**2

In [87]:
test2

array([[25, 25, 49],
       [49,  1, 49],
       [25,  9, 64],
       [36,  0, 49]])